name: flake check
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  check-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v15
        with:
          name: ttak0422-dotfiles-nvim
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: cache inputs
        run: |
          nix flake archive --json \
            | jq -r '.path,(.inputs|to_entries[].value.path)' \
            | cachix push ttak0422-dotfiles-nvim

      - name: flake check
        run: |
          nix flake check
